# Generated by Django 2.0 on 2018-03-09 20:24

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Oeuvre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=250, null=True, verbose_name="Titre de l'oeuvre s'il y en a un")),
                ('ordre', models.IntegerField(blank=True, null=True, verbose_name='Ordre dans sa categorie (optionnel)')),
                ('texte', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="Description ou commentaires sur l'oeuvre")),
                ('periode', models.CharField(blank=True, max_length=250, null=True, verbose_name='Année ou période')),
                ('dimension', models.CharField(blank=True, max_length=250, null=True, verbose_name='Dimensions')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images', verbose_name="Pour les fichiers d'images")),
                ('livret', models.FileField(blank=True, null=True, upload_to='RC', verbose_name='Pour les pdf')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='RCaulet.Categorie', verbose_name="Type d'oeuvre (va être utilisé pour déterminer l'affichage)")),
            ],
            options={
                'ordering': ['titre'],
            },
        ),
    ]
